### ISSUE TITLE
Functions returning PAnsiChar don't work in FullDebugMode

### ISSUE THREAD

**Issue by Wosi** [pleriche/FastMM4#24]
_Platform: Win32
Delphi version: At least from XE6 to 10 Seattle (no more versions tested)_

The following program works well when `FullDebugMode` is off. When you turn on `FullDebugMode` then `function StringToPAnsiChar(const Value: string): PAnsiChar;` returns nonsense. 

    program FullDebugModePAnsiCharError;
    {$APPTYPE CONSOLE}

    uses
      FastMM4,
      System.SysUtils;

    function StringToPAnsiChar(const Value: string): PAnsiChar;
    begin
      Result := PAnsiChar(AnsiString(Value));
    end;

    function StringToPAnsiCharInline(const Value: string): PAnsiChar; inline;
    begin
      Result := PAnsiChar(AnsiString(Value));
    end;

    function StringToPWideChar(const Value: string): PWideChar;
    begin
      Result := PWideChar(Value);
    end;

    var
      TestString: string;
      pAnsiTest: PAnsiChar;
      pWideTest: PWideChar;

    begin
      TestString := 'Test';
      pAnsiTest :=  PAnsiChar(AnsiString(TestString));
      Writeln(pAnsiTest); // Writes: 'Test'
      pAnsiTest := StringToPAnsiChar(TestString);
      Writeln(pAnsiTest); // Writes: Nonsense in FullDebugMode -- Writes : 'Test' if not in FullDebugMode
      pAnsiTest := StringToPAnsiCharInline(TestString);
      Writeln(pAnsiTest); // Writes: 'Test'
      pWideTest := StringToPWideChar(TestString);
      Writeln(pWideTest); // Writes: 'Test'
      readln;
    end.

Is there any chance to get this fixed?

**Comment by pleriche** [comment]
StringToPAnsiChar returns a pointer to the payload of the temporary AnsiString that is no longer valid when the temporary AnsiString gets freed in the epilogue of StringToPAnsiChar. Under FullDebugMode freed blocks are immediately cleared in order to help in tracking down such bugs, which is why you see garbage under FullDebugMode and not outside.
