### ISSUE TITLE
Access violation in 64 bits when calling LogStackTrace (using JCLDebug)

### ISSUE THREAD

**Issue by 64teubs** [pleriche/FastMM4#53]
Hello,

Hunting memory leaks in my application in full debug mode in 64 bits, I have an access violation when LogStackTrace is called from the DLL. Reading the code, I suspect the following line from generating this error:
```GetLocationInfo(Pointer(Cardinal(LAddress) - 1), LInfo);```
Changing it to ```GetLocationInfo(Pointer(LAddress - 1), LInfo);``` fixes the access violation, but maybe there is more to it.

**Comment by PatrickvL** [comment]
Obviously, casting a 64 bit memory address to a 32 bit unsigned integer looses the upper 32 bits, which when set to anything else but zero means the wrong address is used.

**Comment by pleriche** [comment]
Fixed. Thanks!
