### ISSUE TITLE
Add conditional define EnableMemoryLeakReportingUsesQualifiedClassName and support for it

### ISSUE THREAD

**Issue by jpluimers** [pleriche/FastMM4#70]
I propose a new define option `EnableMemoryLeakReportingUsesQualifiedClassName`:

Set this option to use `QualifiedClassName` equivalent instead of `ClassName`
equivalent during memory leak reporting.

This is useful for duplicate class names (like `EConversionError`, which is in
units `Data.DBXJSONReflect`, `REST.JsonReflect` and `System.ConvUtils`,
or `TClipboard` being in `Vcl.Clibprd` and `WinAPI.ApplicationModel.DataTransfer`.

I will post a pull-request for this.

**Comment by baka0815** [comment]
This sounds like a very welcome addition. Please include this!
