### ISSUE TITLE
Runtime-crash when using EnableMemoryLeakReportingUsesQualifiedClassName

### ISSUE THREAD

**Issue by AtlasHackert** [pleriche/FastMM4#88]
I'm on Delphi 7, and I'm getting a runtime-crash on exit when there's a memory leak if EnableMemoryLeakReportingUsesQualifiedClassName has been enabled. The problem is the following line in the AppendClassNameToBuffer function:
UnitName := @PClassData(PByte(LClassInfo) + 2 + PByte(PByte(LClassInfo) + 1)^).UnitName;

Due to either Delphi 7 or my project settings, the pointer arithmetic fails, probably raising an exception that tries to allocate memory, resulting in an invalid operation because the MM has already been uninstalled.

I fixed it by changing the line to:
UnitName := @PClassData(PByte(LClassInfo) + 2 + Integer(PByte(PByte(LClassInfo) + 1)^)).UnitName;

**Comment by PatrickvL** [comment]
Integer must not be used for portable pointer math, use pointer or native int instead.
Also, a few more braces would help in this expression

**Comment by AtlasHackert** [comment]
Good suggestions. Both didn't exist in Delphi 7, hence my lack of knowledge of them. But I see FastMM4.pas defines them, so IntPtr is probably a better choice, yes.

And adding a comment seems smart; I'll leave that up to the developer.

**Comment by AtlasHackert** [comment]
Oops, this issue is sort-of a duplicate: https://github.com/pleriche/FastMM4/issues/87

**Comment by pleriche** [comment]
Hi, I've made a few changes that I believe should fix the issues with Delphi 7 and older.

**Comment by AtlasHackert** [comment]
Confirmed: your change works perfectly in my Delphi 7.

**Comment by pleriche** [comment]
Thank you for the feedback. Closing the ticket.
